// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WepApi.Data;

#nullable disable

namespace WepApi.Migrations
{
    [DbContext(typeof(MySQLDbContext))]
    [Migration("20250816144325_MasterItemUniqlo")]
    partial class MasterItemUniqlo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Models.MasterItemUniqlo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("uniqlo_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("FabricCode")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fabric_code");

                    b.Property<string>("FabricColor")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fabric_color");

                    b.Property<string>("FabricDesc")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fabric_desc");

                    b.Property<string>("GreigeCode")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("greige_code");

                    b.Property<string>("GreigeDesc")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("greige_desc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("type");

                    b.Property<string>("UniqloCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("uniqlo_code");

                    b.Property<string>("UniqloColor")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("uniqlo_color");

                    b.Property<string>("UniqloDesc")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uniqlo_desc");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("master_item_uniqlo");
                });
#pragma warning restore 612, 618
        }
    }
}
